server:
  port: 10010 #网关端口

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: page-service # 路由标示，必须唯一
          uri: lb://pageservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            # 路径断言，判断路径是否是以/user开头，如果是则符合
            - Path=/comment/**,/cinema/**,/film/**,/index/**,/message/**,/mine/**,/order/**,/pay,/alipayNotifyNotice,/alipayReturnNotice,/user/**
      default-filters:
        - AddRequestHeader=Truth,Itcast is freaking awesome!